dist: xenial
language: php

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.3
          name: "Code style"
          env: CHECK_CS=true
        - php: 7.3
          name: "Unit tests"
          env: UNIT_TESTS=true 
        - php: 7.3
          name: "System information browser tests"
          env:     
            - APP_ENV=behat
            - APP_DEBUG=1
            - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/selenium.yml"
            - BEHAT_OPTS="--profile=adminui --suite=adminui --tags=@systemInformation -c=behat_ibexa_oss.yaml"
            - PROJECT_VERSION=^4.0.x-dev

# test only on matching branches (+ Pull requests)
branches:
    only:
        - master
        - /^\d.\d+$/

notifications:
  slack:
    rooms:
      - secure: "2f0W8DM1YKXN/AHjSTYKExKxss+XUrSqATrl2yrGr0qJAwTHxVZSfXCgpHqbKk3bSMeS08/xg5hsk4i5H0MBZVcqYNyP6XvKQ+8IlO9KCXrKbw6iK/9iPnG795wDbqyF9Aj0M5CzJ1AP3flR1/fuaq4at1Oyv7g5CUcHn/WigR262ByWuCEiCfJGAYDyEZ35WpE+LBDqVQ1fIhEThRxOnZH4EQpdY7wzKh8Ujo4V0c465OT6mcJ7XWkrJAcc0MVPpUP6Cgov9Nkc4Ahrdsv128LW6Mvb2Cf4wcrm1QUjeqoVcVb3Zm4h4ve4Px3nPP82wYgrDbe/eD2PUU0XRcmqYr7MTxjhieW/Eq6P5lY/peROb3WQrG0WNoFNWKciiNFOBgJ5xJyENMe77dt2ZJ2G/tqZ3/VWBAzmUoAFX0X2EXB3qMfNK1dnBzUrbBaG7C1UQLEvpV7PfHJB8inss+i29844lKxdJTDiilHMFEfyVbjXK/CsQlz7lqzgyGlPvr4iT9WW1x2UuRJlZDS0GRHGWaPZe8S+LRIP0o7k/MKsaIBO+sxm52UDWBwXbRz5FFHV26TG8d7HHvPUa3sXI4xGePcdW1qare4o+92ivmzxMLgQ+LZP2Pro+t+pTchotyeOgO7umZOQXPR5t92afxyewEQ8mpzo+1CDDfxp14tRcn4="
    on_success: change
    on_failure: always
    on_pull_requests: false

before_script:
    - travis_retry composer selfupdate
    # Avoid memory issues on composer install
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    # Install packages
    - travis_retry composer install --prefer-dist --no-interaction
    - if [ "${BEHAT_OPTS}" != "" ]; then ./vendor/bin/prepare_project_edition.sh oss ${PROJECT_VERSION} ${COMPOSE_FILE} ; fi

script:
    - if [ "${UNIT_TESTS}" != "" ] ; then php vendor/bin/phpunit ; fi
    - if [ "$CHECK_CS" != "" ]; then ./vendor/bin/check_cs.sh; fi
    - if [ "${BEHAT_OPTS}" != "" ] ; then cd "$HOME/build/project"; docker-compose exec --user www-data app sh -c "vendor/bin/ezbehat ${BEHAT_OPTS}" ; fi

after_failure:
  # Will show us the last bit of the log of container's main processes
  # (not counting shell process above running php and behat)
  # NOTE: errors during docker setup of travis build won't show up here (can't output all as it is too much in debug/verbose mode)
  - docker-compose logs -t --tail=15
  # Will show us what is up, and how long it's been up
  - docker ps -s

after_script:
  - if [ "${BEHAT_OPTS}" != "" ] ; then vendor/bin/ezreport ; fi
