parameters:
    ezsettings.default.system_info_view: {}
    ezsettings.global.system_info_view:
        pjax_tab:
            ibexa:
                template: '@@ibexadesign/system_info/my_ibexa.html.twig'
                match:
                    SystemInfo\Identifier: 'ibexa'
            composer:
                template: '@@ibexadesign/system_info/composer.html.twig'
                match:
                    SystemInfo\Identifier: 'composer'
            database:
                template: '@@ibexadesign/system_info/repository.html.twig'
                match:
                    SystemInfo\Identifier: 'repository'
            hardware:
                template: '@@ibexadesign/system_info/hardware.html.twig'
                match:
                    SystemInfo\Identifier: 'hardware'
            php:
                template: '@@ibexadesign/system_info/php.html.twig'
                match:
                    SystemInfo\Identifier: 'php'
            symfony_kernel:
                template: '@@ibexadesign/system_info/symfony_kernel.html.twig'
                match:
                    SystemInfo\Identifier: 'symfony_kernel'
            services:
                template: '@@ibexadesign/system_info/services.html.twig'
                match:
                    SystemInfo\Identifier: 'services'
            invalid:
                template: '@@ibexadesign/system_info/invalid.html.twig'
                match:
                    SystemInfo\Identifier: 'invalid'
